from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Literal, Tuple


# Fixed model identity
MODEL_NAME: str = "mf_ct_scores_clinical_3d"
MODEL_DISPLAY_NAME: str = "3D handcrafted radiomics signature (CT + MF)"
TASK_NAME: str = "sarcopenia_composite_cls"
TASK_KIND: Literal["classification"] = "classification"

# Maps contributing score-stage estimators in this model
SCORE_MAP_NAMES: Tuple[str, ...] = ("musclefat", "ct")

# Clinical features used in the combined stage
CLINICAL_FEATURES: Tuple[str, ...] = "sex"


# Score-level display labels
# These are the combined-stage feature names
SCORE_LEVEL_LABELS: Dict[str, str] = {
    "score__musclefat_signature_3d": "Muscle fat score",
    "score__ct_signature_3d": "CT score",
    "sex": "Sex",
}

# Feature-level display labels (optional manual lookup).
# If a feature name is found here it will be used as-is.
# For names NOT in this dict the label is auto-generated by splitting on "_"
# and placing each part on a new line.
# Set to an empty dict {} to rely entirely on auto-labelling.
FEATURE_LEVEL_LABELS: Dict[str, str] = {
    # Examples — fill in as needed:
    # "original_glcm_Idn_musclefat": "GLCM\nIDN\n(MuscleFat)",
    # "wavelet-H_firstorder_Mean_musclefat": "Wavelet-H\nMean\n(MuscleFat)",
}


# Bootstrap settings
@dataclass(frozen=True)
class BootstrapConfig:
    n_boot: int = 2000
    random_state: int = 42
    # If True, bootstrap p-values are omitted from plots/tables and only
    # the 95 % CI is reported (common for regularised models in radiology).
    omit_pvalues: bool = False


# Plot styling
@dataclass(frozen=True)
class PlotConfig:
    dpi: int = 300
    # Figure size (width, height) in inches for forest plots
    forest_figsize: Tuple[float, float] = (14.0, 5.5)
    # Figure size for SHAP bee swarm plots
    shap_figsize: Tuple[float, float] = (9.0, 5.5)
    # Colour for sarcopenic / non-sarcopenic dots in SHAP bee swarm
    shap_color_high: str = "#D62728"  # red  – high feature value
    shap_color_low: str = "#1F77B4"  # blue – low feature value
    # Font sizes
    fontsize_title: int = 9
    fontsize_axis: int = 7
    fontsize_tick: int = 7
    fontsize_annotation: int = 7


# Paths
_REPO_ROOT = Path(__file__).resolve().parents[2]
_OUTPUT_ROOT = _REPO_ROOT / "output"


@dataclass(frozen=True)
class PathsConfig:
    # Ground truth tables (external, private patient data — not part of the repo)
    gt_table_cohort1: Path = Path(
        "/home/gkolokolnikov/PhD_project/vault_data/SarcopeniaData/table/ground_truth.xlsx"
    )
    gt_table_cohort2: Path = Path(
        "/home/gkolokolnikov/PhD_project/vault_data/SarcopeniaDataLiver/table/ground_truth.xlsx"
    )

    # Feature tables from stage 05
    feature_root: Path = _OUTPUT_ROOT / "05_02_spectral_radiomics_signature_3d"

    # Saved models from stage 06_02_02
    models_dir: Path = _OUTPUT_ROOT / "06_02_02_spectral_radiomics_signature_3d" / "models" / "cls"

    # Saved coefficient tables from stage 06_02_02
    coeff_table: Path = (
        _OUTPUT_ROOT
        / "06_02_02_spectral_radiomics_signature_3d"
        / "tables"
        / "coefficients_sarcopenia_composite_cls.csv"
    )

    # Output root for this stage
    output_root: Path = _OUTPUT_ROOT / "07_07_interpretability"

    @property
    def tables_dir(self) -> Path:
        return self.output_root / "tables"

    @property
    def plots_dir(self) -> Path:
        return self.output_root

    def make_all(self) -> None:
        for d in [self.output_root, self.tables_dir]:
            d.mkdir(parents=True, exist_ok=True)


# Master config
@dataclass(frozen=True)
class InterpretabilityConfig:
    paths: PathsConfig = field(default_factory=PathsConfig)
    bootstrap: BootstrapConfig = field(default_factory=BootstrapConfig)
    plot: PlotConfig = field(default_factory=PlotConfig)


ICFG = InterpretabilityConfig()
